#!/bin/bash

# don't create .pyc/__pycache__ files/dirs. these clutter up the deployment
# system and can cause caching and permissions issues that are hard to debug.
export PYTHONDONTWRITEBYTECODE=1

# select the virtual environment
export VIRTUALENV=/netops/venv/example-web
export PATH=$VIRTUALENV/bin:$PATH

exec $VIRTUALENV/bin/python3 $VIRTUALENV/bin/gunicorn example.loader:app "$@"
